version: '3.8'

services:
  app:
    image: thunder
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
    networks:
      - appnetwork

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Eridani@Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
