// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectTest.Infrastructure.Data.Context;

#nullable disable

namespace ProjectTest.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ProjectTestContext))]
    [Migration("20241022233115_AlterarItensVenda")]
    partial class AlterarItensVenda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectTest.Domain.Entities.AcessoUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasComment("When this entity was created in this DB");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("created_by_user_id")
                        .HasComment("The id of the user who did create");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at")
                        .HasComment("When this entity was deleted in this DB");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("deleted_by_user_id")
                        .HasComment("The id of the user who did the delete");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("The field that identifies that the entity was deleted");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasComment("When this entity was modified the last time");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("update_by_user_id")
                        .HasComment("The id of the user who did the last modification");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("acesso_usuario", (string)null);
                });

            modelBuilder.Entity("ProjectTest.Domain.Entities.ItemVenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Cancelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelada");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasComment("When this entity was created in this DB");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("created_by_user_id")
                        .HasComment("The id of the user who did create");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at")
                        .HasComment("When this entity was deleted in this DB");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("deleted_by_user_id")
                        .HasComment("The id of the user who did the delete");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("desconto");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("The field that identifies that the entity was deleted");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_produto");

                    b.Property<Guid>("ProdutoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("quantidade");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasComment("When this entity was modified the last time");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("update_by_user_id")
                        .HasComment("The id of the user who did the last modification");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_unitario");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("venda_id");

                    b.HasKey("Id");

                    b.HasIndex("VendaId");

                    b.ToTable("item_venda", (string)null);
                });

            modelBuilder.Entity("ProjectTest.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasComment("When this entity was created in this DB");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("created_by_user_id")
                        .HasComment("The id of the user who did create");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at")
                        .HasComment("When this entity was deleted in this DB");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("deleted_by_user_id")
                        .HasComment("The id of the user who did the delete");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("The field that identifies that the entity was deleted");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("senha");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasComment("When this entity was modified the last time");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("update_by_user_id")
                        .HasComment("The id of the user who did the last modification");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("ProjectTest.Domain.Entities.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("Cancelada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("cancelada");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasComment("When this entity was created in this DB");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("created_by_user_id")
                        .HasComment("The id of the user who did create");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_venda");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deleted_at")
                        .HasComment("When this entity was deleted in this DB");

                    b.Property<string>("DeletedByUserId")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("deleted_by_user_id")
                        .HasComment("The id of the user who did the delete");

                    b.Property<string>("Filial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("filial");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted")
                        .HasComment("The field that identifies that the entity was deleted");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nome_cliente");

                    b.Property<long>("NumeroVenda")
                        .HasColumnType("bigint")
                        .HasColumnName("numero_venda");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_at")
                        .HasComment("When this entity was modified the last time");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("update_by_user_id")
                        .HasComment("The id of the user who did the last modification");

                    b.HasKey("Id");

                    b.ToTable("venda", (string)null);
                });

            modelBuilder.Entity("ProjectTest.Domain.Entities.AcessoUsuario", b =>
                {
                    b.HasOne("ProjectTest.Domain.Entities.Usuario", "Usuario")
                        .WithMany("AcessosUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjectTest.Domain.Entities.ItemVenda", b =>
                {
                    b.HasOne("ProjectTest.Domain.Entities.Venda", "Venda")
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ProjectTest.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AcessosUsuarios");
                });

            modelBuilder.Entity("ProjectTest.Domain.Entities.Venda", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
